### ISSUE TITLE
'?' in tlg id

### ISSUE THREAD

**Issue by annakrohn** [PerseusDL/catalog_pending#1]
For the Alexander Ephesius, there is a '?' in the work id.

https://github.com/PerseusDL/catalog_pending/blob/master/mods/Alexander%20Ephesius/AlexanderEphesius.FHG3.Fragmenta.mods.xml#L42

Is this a special case that I need to account for?

**Comment by AlisonBabeu** [comment]
This is a legacy issue that was fixed long ago so I am closing it.
