### ISSUE TITLE
PHI id in catalog_pending/mods/Accius/accius.GRF.Fragmenta.mods.xml?

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/catalog_pending#18]
@AlisonBabeu  Do you have a value for it yet? Right now it's ```<identifier type="phi">400.?</identifier>``` and I can't process that.

**Comment by AlisonBabeu** [comment]
Sigh. This is actually three works here, it was supposed to get broken up into three records and I never did (see then note)
`  <!-- NEED TO BREAK THESE WORKS IN TO RESPECTIVE PHIs -->`
If you don't mind I will do that now and then you will have three MODS to process, doesn't that sound fun?

**Comment by AlisonBabeu** [comment]
This should be fixed by my most recent commit.

**Comment by cwulfman** [comment]
Got it! thanks.

**Comment by cwulfman** [comment]
I can't write to this repository:

> 10:19 $ git push origin master
ERROR: Permission to PerseusDL/catalog_pending.git denied to cwulfman.
fatal: Could not read from remote repository.

> Please make sure you have the correct access rights
and the repository exists.

That's going to make it difficult to work on this data.

**Comment by cwulfman** [comment]
Yep -- got it. Thanks! (And I just fixed a typo in an element name; do a pull from the master branch...)

**Comment by AlisonBabeu** [comment]
Just did. Thanks. Will be committing some files myself in a few minutes
