### ISSUE TITLE
(tlg0082.tlg003.1st1K-grc1) new edition added

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_pending#31]
see https://github.com/OpenGreekAndLatin/First1KGreek/pull/2229

I did some additional cleanup on the cts metadata files to add Greek titles and noticed there was some volume/edition inconsistency in these headers. You may want to double check both my titles and that info.

I used http://schmidhauser.us/apollonius/works/ to get the correct Greek for these (did not use the lunate sigma).

**Comment by AlisonBabeu** [comment]
I will take a look at these files soon, thanks for double checking all of the volume edition metadata as well.

**Comment by AlisonBabeu** [comment]
Hi @lcerrato , so I don't think 16 months later qualifies as soon alas but I double checked the metadata on HathiTrust and have hopefully corrected all of the data. I added in series metadata to help make it clearer.

**Comment by AlisonBabeu** [comment]
As the corrected files have been merged I'm closing this issue.
