### ISSUE TITLE
Do we want CTS urns in our MADS records?

### ISSUE THREAD

**Issue by annakrohn** [PerseusDL/catalog_pending#4]
Up until now we have only included the tlg/phi/stoa ids, and then the CITE urn for the resulting CITE row.  I'll have to update the logic if we do want CTS urns.  The following have it:

https://github.com/PerseusDL/catalog_pending/blob/master/mads/Abydenus%20Historicus/viaf102377847.mads.xml
https://github.com/PerseusDL/catalog_pending/blob/master/mads/Asclepiades%20Myrleanus/viaf29920397.mads.xml
https://github.com/PerseusDL/catalog_pending/blob/master/mads/Ateius%20Capito/nr95039375.madsxml.xml
https://github.com/PerseusDL/catalog_pending/blob/master/mads/Evagrius%20Monachus/nr96044291.madsxml.xml
https://github.com/PerseusDL/catalog_pending/blob/master/mads/Phoronis/phoronis.mads.xml
https://github.com/PerseusDL/catalog_pending/blob/master/mads/Ptolemaeus%20Megalopolitanus/viaf37304981.mads.xml
https://github.com/PerseusDL/catalog_pending/blob/master/mads/Sinnius%20Capito/nr95027981.madsxml.xml
https://github.com/PerseusDL/catalog_pending/blob/master/mads/Socrates%20Rhodius/viaf71784002.mads.xml
https://github.com/PerseusDL/catalog_pending/blob/master/mads/Timagenes/viaf59476397.mads.xml

**Comment by balmas** [comment]
it looks like this should have been closed.
