### ISSUE TITLE
(tlg1750.tlg001 - tlg004) new texts

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_pending#46]
I've created a new set of files for Vitae Prophetarum. The edition is identical, as are the titles/labels below. Thanks!!

tlg1750.tlg001
  `<ti:title xml:lang="lat">De prophetarum vita et obitu (Dorothei recensio)</ti:title>`
  `<ti:edition urn="urn:cts:greekLit:tlg1750.tlg001.1st1K-grc1" workUrn="urn:cts:greekLit:tlg1750.tlg001">`
    `<ti:label xml:lang="lat">De prophetarum vita et obitu (Dorothei recensio)</ti:label>`
    `<ti:description xml:lang="mul">Vitae Prophetarum. Prophetarum vitae fabulosae. Schermann, Theodorus, editor. Leipzig: Teubner, 1907.</ti:description>`

tlg1750.tlg002
  `<ti:title xml:lang="lat">De prophetarum vita et obitu (recensio anonyma)</ti:title>`
  `<ti:edition urn="urn:cts:greekLit:tlg1750.tlg002.1st1K-grc1" workUrn="urn:cts:greekLit:tlg1750.tlg002">`
    `<ti:label xml:lang="lat">De prophetarum vita et obitu (recensio anonyma)</ti:label>`
    `<ti:description xml:lang="mul">Vitae Prophetarum. Prophetarum vitae fabulosae. Schermann, Theodorus, editor. Leipzig: Teubner, 1907.</ti:description>`

tlg1750.tlg003
`<ti:title xml:lang="lat">De prophetarum vita et obitu (recensio scholiis Hesychii aliorumque patrum in prophetas adjecta)</ti:title>`
 ` <ti:edition urn="urn:cts:greekLit:tlg1750.tlg003.1st1K-grc1" workUrn="urn:cts:greekLit:tlg1750.tlg003">`
   ` <ti:label xml:lang="lat">De prophetarum vita et obitu (recensio scholiis Hesychii aliorumque patrum in prophetas adjecta)</ti:label>`
    `<ti:description xml:lang="mul">Vitae Prophetarum. Prophetarum vitae fabulosae. Schermann, Theodorus, editor. Leipzig: Teubner, 1907.</ti:description>`

tlg1750.tlg004
  `<ti:title xml:lang="lat">Index apostolorum discipulorumque Domini</ti:title>`
  `<ti:edition urn="urn:cts:greekLit:tlg1750.tlg004.1st1K-grc1" workUrn="urn:cts:greekLit:tlg1750.tlg004">`
    `<ti:label xml:lang="lat">Index apostolorum discipulorumque Domini</ti:label>`
   ` <ti:description xml:lang="mul">Vitae Prophetarum. Prophetarum vitae fabulosae. Schermann, Theodorus, editor. Leipzig: Teubner, 1907.</ti:description>`

**Comment by AlisonBabeu** [comment]
Hi @lcerrato I've added the metadata for this edition to inverted.mods.xml and committed it to GitHub. So I'm going to close this issue.
