### ISSUE TITLE
(phi0929.phi001) duplicates and new edition

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_pending#47]
I see two catalog entries that seem to be for the same edition.
https://catalog.perseus.org/cite-collections/versions/search?utf8=✓&field_type=version&search=phi0929.phi001

It seems like the SLUB edition got it's own URN?

I was just going to bump that for phi0929.phi001.ogl-lat1.xml but I don't want to bump a duplicate.

So, I just created:

`<ti:edition urn="urn:cts:latinLit:phi0929.phi001.ogl-lat1" workUrn="urn:cts:latinLit:phi0929.phi001" xml:lang="lat">`
`<ti:label xml:lang="lat">De chorographia</ti:label>`
`<ti:description xml:lang="mul">Pomponius Mela. Pomponius Melae De chorographia libri tres. Frick, Karl, editor. Leipzig: Teubner, 1935.</ti:description>`
`</ti:edition>`

**Comment by AlisonBabeu** [comment]
Hi @lcerrato you are quite right in that they are the same edition but are different printings. The opp-lat3 is an editio stereotypis that was printed in 1935 whereas opp-lat2 was printed in 1880.  When I created the catalog record for the second printing, we didn't have a good way of of expressing relationships between separate printings in a single catalog record (and still don't really). It was also cataloging practice at the time to have a new URN for anything that might be considered a new manifestation/physical printing even if it was the same exact edition.  I think using ogl as the main namespace(?) for all new Latin texts for the OGL is a very solid plan.  Using OGL is a good way to indicate that the URN is for a version of a text that is not just a link to a digitized copy.

**Comment by lcerrato** [comment]
@AlisonBabeu 
Yes, the cite collection table display does not show the print date, so I didn't realize these were different. I would agree that they are probably something that could be consolidated in the data. 

Something like `date type="printing"` so perhaps there could be that sort of refinement in other data in the future. There's also an `edition` tag as well, which can further refine this in our text metadata or headers.

I am using the URN assigned when this was entered into the workflow via Trello this summer— not my URN or namespace. I inherited this with the file. 

Thanks.

**Comment by AlisonBabeu** [comment]
Hey @lcerrato I am still working out the best way to consolidate in MODS, but having most of the data in two files helps.  I think OGL was agreed upon by one group or another at some point but I think it works.

**Comment by lcerrato** [comment]
Yes, I have no idea what I'm doing . . .  as long as you have the info you need!!

**Comment by AlisonBabeu** [comment]
As both of these editions are cataloged I'm closing this issue.
