### ISSUE TITLE
(tlg1805.tlg001-tlg010) ogl greek new editions 

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_pending#48]
@AlisonBabeu 
tlg1805.tlg001.1st1K-grc1.xml - tlg1805.tlg010.1st1K-grc1.xml
have been added see https://github.com/OpenGreekAndLatin/First1KGreek/pull/2286

There was some disagreement on the `author` tag — I noted that this is is more of a `workgroup` and should not be thought of as an author per se.

I suggest checking in with the UVa group on this as apparently they had a big discussion on this that I was unaware of at the time of the metadata creation. So these are checked in as is but need further work.

It's not my call as to how these are presented — I did my best according to TLG but  the UVa team disagrees with the TLG presentation.

**Comment by AlisonBabeu** [comment]
I have created metadata for these works @lcerrato. I will close this issue when the works are fully committed to GitHub and Scaife.

**Comment by AlisonBabeu** [comment]
Closing this issue, works are in Scaife and have metadata in GitHub.
