### ISSUE TITLE
Missing tlg ids

### ISSUE THREAD

**Issue by annakrohn** [PerseusDL/catalog_pending#5]
https://github.com/PerseusDL/catalog_pending/blob/master/mods/Chaereas/Chaereas.FHG3.Fragmenta.mods.xml#L45

https://github.com/PerseusDL/catalog_pending/blob/master/mods/Onomacritus/onomacritus.EGF.mods.xml#L27

https://github.com/PerseusDL/catalog_pending/blob/master/mods/Pisinus/Pisinus.Fragmenta.EGF.mods.xml#L28

**Comment by AlisonBabeu** [comment]
This issue was address by the ability of the catalog to ingest non standard IDs so I am closing it.
