### ISSUE TITLE
(new URN - tlg2948.tlg001.1st1K-eng1) Acts of Philip

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_pending#51]
This has been assigned tlg2948.tlg001.1st1K-grc1.xml but it is an English translation by MR James, so at the very least it should be tlg2948.tlg001.1st1K-eng1.xml

Is that ok or is there something else using that URN?

Also note that the spelling Phillip was used in the header, but I see Philip in the text. I don't know why the former would be used but it might need to be addressed in the catalog.

**Comment by lcerrato** [comment]
see https://github.com/OpenGreekAndLatin/First1KGreek/issues/2272

**Comment by AlisonBabeu** [comment]
hi @lcerrato there is no other text using that URN since this will be the first edition of this work for the catalog_data. The spelling should be Acta Philippi (that's in the TLG, I had it wrong in the spreadsheet and have since corrected it). For some reason I am incapable of spelling Philip correctly, I always want it to have two l's and possibly four or more p's. :)

**Comment by lcerrato** [comment]
Thanks! This is the English file, so the title in the xml header had two Ls. I don't think that was anything to do with you.
The English file is not in the spreadsheet, as far as I can tell.
I do not see any records for any of these MR James translations.

**Comment by lcerrato** [comment]
cts workgroup 
`<ti:groupname xml:lang="lat">Acta Philippi</ti:groupname>`

work level metadata:
`<ti:title xml:lang="lat">Acta Philippi</ti:title>`

  `<ti:translation urn="urn:cts:greekLit:tlg2948.tlg001.1st1K-eng1" workUrn="urn:cts:greekLit:tlg2948.tlg001" xml:lang="eng">`
    `<ti:label xml:lang="eng">Acts of Philip</ti:label>`
    `<ti:description xml:lang="mul">Acts of Philip. The Apocryphal New Testament, being the Apocryphal Gospels, Acts, Epistles, and Apocalypses. James, Montague Rhodes, translator. Oxford: Clarendon Press, 1924.</ti:description>`

**Comment by AlisonBabeu** [comment]
I  have created metadata for this edition so I am closing this issue.
