### ISSUE TITLE
(tlg1286.tlg001-tlg020 exc tlg015) new work

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_pending#52]
This is a large batch of Corpus Hermeticum files. 
https://github.com/OpenGreekAndLatin/First1KGreek/pull/2292

There are title/author issues that should be re-checked, so I won't cut and paste everything here.

You may want to check these once the ingest is complete.

Note that one of the files is in Latin, so I changed the URN to reflect that but I'm not sure if that is followed elsewhere in OGL/1st1k.

**Comment by AlisonBabeu** [comment]
hi @lcerrato I will take a look at all these files once the ingest is complete and will start working on the metadata this week.

**Comment by AlisonBabeu** [comment]
Hi @lcerrato I've created metadata for all these files and committed them to Github in inverted.mods.xml so I am closing this issue.
