### ISSUE TITLE
(stoa0367.stoa001.ogl-lat1.xml) URN needed for Fracco Fasti

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_pending#57]
https://www.worldcat.org/title/ambrosii-novidii-fracci-ferentinatis-sacrorum-fastorum-libri-xii/oclc/4013894

Ambrogio Fracco (called Novidius)
https://viaf.org/viaf/295136602/#Fracco,_Ambrogio_Novidio

Sacrorum fastorum libri XII

Romae, apud A. Bladum, 1547

Do you have a last used stoa ID so we know where to pick up? or perhaps an OGL identifier or the VIAF?

**Comment by AlisonBabeu** [comment]
Unfortunately I don't have any IDs for this author, the STOA created a few IDs for a number of later Latin authors but not for this individual. I'm increasingly torn as to what to do in these cases. I created that STOA ID for Thibault and could do so for this author, but the STOA numbers with letters creates such weird looking IDs. I'm increasingly wondering if for entirely new authors for OGL if we should just start a new namespace that we could maybe ultimately map other Latin STOA authors onto, such as ogl0001.ogl001. The VIAF IDS are just so cumbersome as you have pointed out previously.  Any thoughts?

**Comment by lcerrato** [comment]
No. Unless they just create a UVA namespace? I’m a little troubled by being the gatekeepers for this. 
If there is no tracking mechanism, such as a list, this could become unmanageable.

**Comment by AlisonBabeu** [comment]
Yeah I know. I guess I will go with a STOA ID for now, so the next number would be stoa0367 since I've decided to stop with letters after numbers (except for the last one). So let's go with stoa0367 for this author and then stoa0367.stoa001.ogl-lat1 since I have no cataloged editions of this author.  Does that work?

**Comment by lcerrato** [comment]
I have no objections to any part of it but I wish I could make better on the spot recommendations so we aren't spending so much bandwidth on these questions.
I'm not even sure if this is strictly an OGL project, is it?
I think part of it has to rest with UVa — just to make sure the namespace is ok.

**Comment by AlisonBabeu** [comment]
I suppose it is not strictly an OGL project but I kind of hate the idea of yet another URN ender floating out there beyond 1st1K, opp, and perseus, and we have used OGL before for some other Latin texts.  For placeholder purposes hopefully that URN could work?

**Comment by lcerrato** [comment]
It's fine by me!
I just was thinking that if UVa has its own namespace, then they can mint them as they go in these special cases. I'm trying to think of ways to make it less burdensome.

**Comment by lcerrato** [comment]
stoa0367.stoa001.ogl-lat1  it is!
Should I leave this opening for cataloging purposes.

**Comment by AlisonBabeu** [comment]
Yes, thanks!

**Comment by lcerrato** [comment]
This text has been completed here
https://github.com/OpenGreekAndLatin/Latin/issues/22

```
<ti:work xmlns:ti="http://chs.harvard.edu/xmlns/cts" groupUrn="urn:cts:latinLit:stoa0367" xml:lang="lat" urn="urn:cts:latinLit:stoa0367.stoa001">
    <ti:title xml:lang="lat">Sacrorum Fastorum Libri XII</ti:title>
    
    <ti:edition urn="urn:cts:latinLit:stoa0367.stoa001.ogl-lat1" workUrn="urn:cts:latinLit:stoa0367.stoa001" xml:lang="lat">
        <ti:label xml:lang="lat">Sacrorum Fastorum Libri XII</ti:label>
        <ti:description xml:lang="mul">Ambrogio Novidio Fracco. Ambrosii Novidii Fracci Ferentinatis Sacrorum fastorum libri XII. Rome: M. Antonius Bladus Asulanus, 1547.</ti:description>
    </ti:edition>
</ti:work>
```

```
<ti:textgroup xmlns:ti="http://chs.harvard.edu/xmlns/cts" projid="latinLit:stoa0367" urn="urn:cts:latinLit:stoa0367">
    <ti:groupname xml:lang="lat">Ambrogio Novidio Fracco</ti:groupname>
</ti:textgroup>
```

**Comment by AlisonBabeu** [comment]
I've created a catalog record for this work so I"m closing this issue.
