### ISSUE TITLE
ID discrepancies 

### ISSUE THREAD

**Issue by annakrohn** [PerseusDL/catalog_pending#6]
We've got two different ids for Heron, flg0413 (https://github.com/PerseusDL/catalog_pending/blob/master/mads/Heron%20of%20Athens/heron.mads.xml) and flg0433 (https://github.com/PerseusDL/catalog_pending/blob/master/mods/Heron%20Atheniensis/Heron.FHGIV.mods.xml).

**Comment by AlisonBabeu** [comment]
Fixed the authority record for fhg433. Thanks for catching this.
