### ISSUE TITLE
(new edition) tlg2949.tlg001.1st1K-grc1

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_pending#63]
`  <ti:edition urn="urn:cts:greekLit:tlg2949.tlg001.1st1K-grc1" workUrn="urn:cts:greekLit:tlg2949.tlg001" xml:lang="grc">`
`    <ti:label xml:lang="grc">Περίοδοι καὶ μαρτύριον τοῦ ἁγίου Βαρνάβα τοῦ ἀποστόλου</ti:label>`
`    <ti:description xml:lang="mul">Acta Philippi et Acta Thomae accedunt Acta Barnabae. Bonnet, Maximilian, editor. Leipzig: Hermannus Mendelssohn, 1903.</ti:description>`
`  </ti:edition>`

**Comment by AlisonBabeu** [comment]
Ive added catalog metadata for this edition so I'm closing this issue.
