### ISSUE TITLE
An issue with how host/constituent records are created from the ingest process

### ISSUE THREAD

**Issue by AlisonBabeu** [PerseusDL/catalog_pending#7]
This is an issue with several related issues. 

First, a MODS record was ingested in the last import but it only created one component work record. The record in question was for Hierocles of Alexandria. The full MODS record at import can be seen [here](https://github.com/PerseusDL/catalog_pending/commit/7817e3e72a144f54f1a97fe8b39fdcb4da5475b6).

While it successfully created an authority record for the top level author [Hierocles](https://github.com/PerseusDL/catalog_data/blob/master/mads/PrimaryAuthors/H/Hierocles%20of%20Alexandria/Hierocles.mads.xml) as well as for the `<relatedItem type="constituent">` record by Pythagoras for Carmen Aurem found [here] (https://github.com/PerseusDL/catalog_data/blob/32c875c032dc0fb17a380f7db2748e61368019b0/mods/greekLit/tlg0632/tlg001/opp-grc4/tlg0632.tlg001.opp-grc4.mods1.xml), yet it did not create a MODS record for the actual edition by Hierocles even though there was a TLG identifier `<mods:identifier type="tlg">2571.001</mods:identifier>` in the record.

I'm wondering if this has something to do with the fact that the code is maybe set up to only handle one TLG identifier per individual MODS file unless it finds those separate TLGs (or any other identifier perhaps) in individual  `<relatedItem type="constituent">` records within that MODS. I only created the one constituent record in this MODS record because the work by Hierocles is the entire edition and the work by Pythagoras was tucked away in the preface. Or perhaps something else entirely caused this to happen.

**Comment by balmas** [comment]
this issue belongs on the cite_collections_rails repo since that's where the update code is. I'm going to copy it there.
