### ISSUE TITLE
is grc a valid language@objectPart value?

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_pending#8]
@AlisonBabeu  I've encountered something I'm not sure about wrt to handling of language when importing a mods file

This file in catalog pending has a language element with an objectPart value of 'grc':
 correct for https://github.com/PerseusDL/catalog_pending/blob/master/mods/Herodotus/herodotus.Teubner%28Dietsch-Kallenberg%29.Historiae.mods.xml#L41

We would end up not knowing what language to attribute to the version identified by this mods file, because the the only objectPart value we consider valid is "text". If it didn't have an objectPart at all, then we would use the language specified here, but because it has an objectPart and it isn't text, we assume it's describing something other than the text.

**Comment by AlisonBabeu** [comment]
That is just a plain old error on my part. Whoops.
