### ISSUE TITLE
constituents and no parent

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_pending#9]
@AlisonBabeu another question for you:
For the following record 
https://github.com/PerseusDL/catalog_pending/blob/94e93745ef655cc428ccd1d79ca99bf44d99cb9f/mods/Bible/bible.poetici.stuttgart.pers.mods.xml

Am I correct that the lack of parseable identifier in the parent mods record should NOT prevent us from creating individual mods records for each of the constituent items?  I.e. we want to ONLY create mods records and CTS versions for the constituents for this ?

**Comment by AlisonBabeu** [comment]
I don't believe that it should, and yes you are quite right we do indeed only wish to create MODS records for all of the constituents in this volume.

**Comment by balmas** [comment]
super thanks!
