### ISSUE TITLE
(tlg0656.tlg002.1st1K-grc1) new edition

### ISSUE THREAD

**Issue by charhoughton** [PerseusDL/catalog_pending#95]
`` <ti:edition urn="urn:cts:greekLit:tlg0656.tlg002.1st1K-grc1" workUrn="urn:cts:greekLit:tlg0656.tlg002">
      <ti:label xml:lang="grc">Περὶ ἀπλῶν φαρμάκων</ti:label>
      <ti:description xml:lang="mul">Dioscorides Pedianus. Pedanii Dioscuridis Anazarbei de materia medica libri quinque, Vol. 1. Wellmann, Max, editor. Berlin: Weidmann, 1907.</ti:description>
  </ti:edition>``

**Comment by lcerrato** [comment]
@charhoughton 
I think that this label should read just Περί απλών φαρμάκων per my note in #2421. This is what is on the title page prior to the text and seems to be the short Greek title.

**Comment by charhoughton** [comment]
got it, thanks for clarifying @lcerrato

**Comment by lcerrato** [comment]
@charhoughton 
Thank you for doing this.

**Comment by charhoughton** [comment]
@lcerrato absolutely, and thank you for your patience. I just pushed another commit with the shortened label.

**Comment by AlisonBabeu** [comment]
And thanks to both of you @charhoughton and @lcerrato for making my life tracking down metadata far easier for our new editions!

**Comment by lcerrato** [comment]
This was all @charhoughton doing the heavy lifting! I just offered some commentary of debatable merit....

**Comment by AlisonBabeu** [comment]
I've created metadata for this work so I'm closing this issue.
